### PR TITLE
Support custom default file name template

### PR DESCRIPTION
**Pull request by codeworm96**
This is my attempt to provide the function described in #872.
I add a new option in the preferences dialog, user can turn this function on and provide a template string to configure the way a new default filename is created.

### CODE REVIEW

**Comment by uliska** [comment]
Thank you for this pull request. I assume you are one of those who reached out to us because of GSoC? It would be good then to know who of them you are ...

One technical issue with your commit: it should *not* include the `.pot` file, so you should re-commit it.

I've tried out your code and at first sight it is very nice - the preference looks good and works, and when using `title` and `composer` it does what is expected upon saving the file.

However, using any other header field in the template string triggers a KeyError exception. This is because it isn't present in the `fields` tuple.

The straightforward solution would be to add all possible header fields to the `fields` tuple, but the problem is that a user can specify arbitrary non-standard header fields and may want to use them in the default filename as well.

So you should try to igenerate the field list from those present in the template string (of course only if the option is activated).

**Comment by codeworm96** [comment]
> I assume you are one of those who reached out to us because of GSoC? It would be good then to know who of them you are ...

Yes. I am seeking a suitable project to apply. After familiarizing myself with frescobaldi and trying to make some contribution. I decide to choose frescobald. I will introduce myself in the mailing list soon. 

> One technical issue with your commit: it should not include the .pot file, so you should re-commit it.

Fixed. I modified that commit to remove the .pot file, so you may need a '--force' option when pulling.

> However, using any other header field in the template string triggers a KeyError exception.

Sorry for my carelessness. An end user application should be as robust as possible against unexpected input. I thought about the problem again. Maybe the format() method is too flexible that user have a lot of ways to construct a template that causes some errors(for example, non-standard header, out-of-range index and extremely long padding). As to this function, maybe a str.replace() is enough? In the fixed code, I just replace supported headers and leave alone unknown headers.

**Comment by uliska** [comment]
Thanks, this is definitely better already, as it prevents the exception.

However, this way it will only support the two fields `title` and `composer` again, which is of course not enough to pass as "custom" ...

I see two possible improvements (actually as said previously):
* add all known header fields to the tuple definition in line 79
* Retrieve all field names from the actual template string and feed these to the tuple

The second one would require some more reworking of the code, but I think this would be the way it should be (because the user can use arbitrary fields if they tend to use them in the header).

**Comment by uliska** [comment]
> I am seeking a suitable project to apply. After familiarizing myself with frescobaldi and trying to make some contribution. I decide to choose frescobald. I will introduce myself in the mailing list soon.

Ah, I thought you were one of those who had already introduced themselves. Well, opening a pull request is a good way to start that process ...

**Comment by uliska** [comment]
Thinking again, it may actually be sufficient to add all header fields that are used by LilyPond's titling. It's about the *preset* filename after all and doesn't limit what can be used in the Save dialog.

**Comment by codeworm96** [comment]
I adopted the second way to allow user to use more fields in their template.
It retrieves all field names from the template string and try to find them in the document now.

**Comment by uliska** [comment]
From *my* POV this is good to go now and I'd like to pass it on to @wbsoft to actually merge it.

One thing that *could* be discussed is the behaviour for unset variable. Instead of evaluating to `-unknown-` it might be suppressed, otherwise I end up with a filename like `My-title-unknown-unknown.ly` - which might be better reflected as simply `My-title.ly`. But I wouldn't make this a requirement for/against merging.

**Comment by wbsoft** [comment]
Thank you, Zhang!, And Urs, for your help! We could fix the 'unknown' thingy if it's needed later.

**Pull request merged**
