### PR TITLE
Creating an instance (with parent) instead of using a static QMessage…

### PR DESCRIPTION
**Pull request by PeterBjuhr**
…Box function

See #688.

### CODE REVIEW

**Comment by PeterBjuhr** [comment]
@fedelibre I can't test this myself, will you give a try?

**Comment by fedelibre** [comment]
I've pulled your branch and run the binary in the git tree, but I can't see any change.
I confirm what I wrote in the issue:

>The focus does not change to this new popup window so using keyboard shortcuts (Alt+...) is not possible. The shortcuts work only after clicking on the popup window, making the shortcuts no more useful at all.

**Comment by PeterBjuhr** [comment]
Thanks! I added a commit with another try at a solution. Can I ask you to test again?

**Comment by fedelibre** [comment]
It doesn't work.. but I've just realized that my report was not correct: the problem arises only when I close Frescobaldi using the `Alt+F4` shortcut. If I use `Ctrl+W`, then the dialog box is on focus and works correctly (also on master, not only in this branch you are working on).

Sorry for this late find!

**Comment by PeterBjuhr** [comment]
I see! How about if you use `Ctrl+Q`, any difference?

**Comment by fedelibre** [comment]
`Ctrl+Q` works correctly as well

**Comment by PeterBjuhr** [comment]
Ok, good. Can you tell what (window) actually has focus when you use `Alt+F4`?

Is `Alt+F4` equivalent of using the x-button to close the window?

**Comment by fedelibre** [comment]
I would say that no window has focus, not even main Frescobaldi window. In fact whatever shortcut I try doesn't work. I made a screenshot:

fresco-alt-f4

**Comment by PeterBjuhr** [comment]
I pushed a new commit in the same branch. Will you try again?

**Comment by fedelibre** [comment]
Same problem unfortunately.
You cannot reproduce it in your system if you use `Alt+F4`?

**Comment by PeterBjuhr** [comment]
No unfortunately I can't - the focus is kept all the way.

**Comment by PeterBjuhr** [comment]
I'm trying out different Qt stuff to try to emulate the behavior in your system. But I can't find any...

**Comment by fedelibre** [comment]
Let me know if I can help you somehow.
Can't you get access to a Gnome 3 desktop? (a friend computer? a live CD?)

**Comment by PeterBjuhr** [comment]
Yes, I was just thinking about that myself! :) I'm interested to try it out anyway...

**Comment by PeterBjuhr** [comment]
Now I have a Debian OS I can test on, and I can reproduce the issue there!

To sum up, if `Alt+F4` is used to close the app the whole application loses focus (Frescobaldi is no longer shown as the active program in the top list) and the user have to activate it again before any shortcuts work.

Any other way of closing the document or the application keeps the app in focus (until it's properly ended).

I have tried different Qt stuff but haven't found anything that can override the system's behavior. And I'm not sure that it's a good idea to do so anyway.

**Comment by wbsoft** [comment]
The screenshot by @fedelibre shows a behaviour (by the window system) where the MessageBox gets no window border but (because the MessageBox is modal) the app is shown darker (because the MessageBox is the only widget that can be dealt with).

That the MessageBox gets no keyboard focus is really a Qt/window system issue. Maybe we can workaround by creating a QMessageBox (`m`) instance by hand and then:
```python
m.show()
m.setFocus(Qt.ActiveWindowFocusReason)
result = m.exec_()
```

**Comment by PeterBjuhr** [comment]
That doesn't work unfortunately. I think basically the problem is not that the message box is not in focus but that the app is not in focus (deactivated by the window system).

But I noticed that if you create the `QMessageBox` without a parent the app remains active in the top list. I'm not sure if that will help us though.

**Comment by PeterBjuhr** [comment]
No new ideas have popped up here. For now the workaround seems to be to use `Ctrl+Q` instead of `Alt+F4`. #688

**Pull request closed without merging**
