### PR TITLE
Loading a default background instead of an empty QUrl, see issue #566

### PR DESCRIPTION
**Pull request by PeterBjuhr**
It looks nicer and we won't get the Script error.

### CODE REVIEW

**Comment by wbsoft** [comment]
Nice. it would be nice if the lily would auto-center and not show scrollbars (unless the lily itself would be bigger than the view). But I don't know if that 'd be possible :-)

**Comment by PeterBjuhr** [comment]
Yes, I agree. I don't know if it's possible either. But what I could do is to not make the image bigger than the lily.

**Comment by PeterBjuhr** [comment]
The image is in 'A4' size now as it is LilyPond's default. 

I guess it would be possible to read the settings of the widget and to adjust the image accordingly.

A much simpler solution would be to remove the lily and only have the grey background (as the Music View). :)

**Comment by wbsoft** [comment]
Try loading this HTML:
```
<html>
<head>
<style type="text/css">
html { 
  background:
  -webkit-linear-gradient(top, rgba(160,160,160,0.7) 0%,rgba(160,160,160,0.7) 100%),
  url(../icons/frescobaldi.svg) no-repeat center center fixed ; 
  -webkit-background-size: cover;
  background-size: cover;
}
</style>
</head>
</html>
```
It can point to the default Frescobaldi icon which will be shown partially transparent (the 0.7; 1.0 is completely transparent).
If you comment the both `background-size` lines, the image will be centered but not streched.

**Comment by PeterBjuhr** [comment]
Thanks! It's much better. The scrollbars are gone. But as I have a rather narrow screen the lily is cropped horizontally.

**Comment by PeterBjuhr** [comment]
Also I get an error because the file isn't an svg.

**Comment by wbsoft** [comment]
We should change `cover` to `contain`...

**Comment by PeterBjuhr** [comment]
Yes, it's better! But I think it's even better to set a percentage value so there is a margin.

I solved the svg error by adding a `svg` tag to the document.

**Comment by wbsoft** [comment]
I think the svg tag complaint comes from the script that's started in svgLoaded after loading the HTML. We should probably not connect to the loaded signal but manually call the javascripts after loading a svg document.

**Comment by wbsoft** [comment]
Sorry, my last comment will be mistaken, load or setUrl return directly, we can install javascripts only when the loading has finished, hence the signal is ok!

**Comment by PeterBjuhr** [comment]
@wbsoft I see you have fixed the loose ends now. Great!

**Pull request merged**
