### PR TITLE
Python3 stable

### PR DESCRIPTION
**Pull request by proski**
Most of my Python 3 patches are not needed anymore. The remaining four patches are still needed.

### CODE REVIEW

**Comment by wbsoft** [comment]
Thank you! I wasn't aware of your patch set. Very welcome!

**Comment by proski** [comment]
​Hi Wilbert,

Sorry, I was sitting on those patches too long without submitting them. On
the other hand, most of your fixed are better than mine. Some of my fixed
are not needed anymore and I cannot understand why. For example, adding
extra arguments to some GUI functions is not needed now:

https://github.com/proski/frescobaldi/commit/436fb829ad01ec11e58c8c580c10ab33b5264f25

The only thing left is complete elimination of basestring. I think the
simplest approach would be to do

isinstance(args, (type(b''), type(u'')))

Also "if sys.version_info[0] == 3" is not good, it will break in Python 4.

Setting "string_types = str" on Python 3 is questionable, it excludes
bytes. Maybe they were supposed to be excluded, but I'd rather see that
logic with a comment where it's applied, not globally on top of the file.

I cannot get PDF to show with Python 3, but it may be a Fedora 21 issue
(poppler compiled for python2 or something like that).

Pavel

**Comment by wbsoft** [comment]
the poppler-qt4 module works with Python3, it just needs to be compiled.

The extra argument issue was because of a bug in signals.py, I fixed couple of days ago.

Indeed the `(type(b''), type(u''))` is a good idea.

And the best version check is `if sys.version_info >= (3, 0):` etc.

One remaining thing is that I can't yet get portmidi/pypm working.

**Comment by dliessi** [comment]
> The only thing left is complete elimination of basestring. I think the simplest approach would be to do
>
> isinstance(args, (type(b''), type(u'')))
>
> Also "if sys.version_info[0] == 3" is not good, it will break in Python 4.
>
> Setting "string_types = str" on Python 3 is questionable, it excludes bytes. Maybe they were supposed to be excluded, but I'd rather see that logic with a comment where it's applied, not globally on top of the file.

If I understand correctly, your comments refer to edc15de8269f34461c21cc1860ead2af3022edfd.
As far as I understand, byte strings *were* meant to be excluded, at least according to https://docs.python.org/3/howto/pyporting.html, which explicitly advises *against* mixing binary data (`b''`) and text (`u''`).

The way I defined `string_types` is exactly how it is defined in [six](https://pypi.python.org/pypi/six), see [its source](https://bitbucket.org/gutworth/six/src/2c4cfe488c5bb03a6f7315025e62242730eeca89/six.py#cl-35).
I preferred to write those few lines instead of adding a dependency on a whole package.

I can change `==` to `>=` in the `if`, and I can add a comment explaining why I wrote that code, but I don't think that I should use `isinstance(args, (type(b''), type(u'')))`.

**Comment by wbsoft** [comment]
Agreed!

**Comment by proski** [comment]
OK, I get it now. In Python 3, every string is unicode. In Python 2, str("") is a non-unicode string (unless str was redefined), whereas "" may be unicode if "from __future__ import unicode_literals" is used. So we want to match both in Python 2, but only Unicode in Python 3. Thank you for the link, it's very useful.

**Comment by proski** [comment]
By the way, frescobaldi under python 3 cannot open files with umlauts. QApplication is instantiated with correct sys.argv in app.py, but QApplication.arguments() in main.py returns arguments with umlauts stripped away. I don't see any locale settings for QApplication. Locale is en_US.UTF-8. Observed on Ubuntu 14.10 and Fedora 21.

**Comment by wbsoft** [comment]
thanks for catching that, i created an issue for that: #562.

**Pull request merged**
