### PR TITLE
Reimplement "Export Audio" using a dialog

### PR DESCRIPTION
**Pull request by proski**
I tested the code carefully, but I don't do much GUI programming, so I'm submitting this patch as a pull request.

As few stylistic questions about the code.

Would it be better to have a separate file for the audio export dialog? Or is the code too trivial for that?

Is it OK to do so many things in the constructor? Or should I move some of that stuff to another function? If so, should it be a slot or just a class method?

Any better ideas what to write in self.setMessage()?

### CODE REVIEW

**Comment by wbsoft** [comment]
Thanks, all changes look good so I merged them.

**Comment by wbsoft** [comment]
Regarding the audio exporting dialog: This dialog is basically about running any external command and examining its output. I'll probably move it to a generic dialog and have the caller set the command etc.

**Comment by proski** [comment]
I agree, it can be generalized. But please note that the code includes logic specific to file generation. The output file is deleted if the operation is canceled.

Why did you add another call to setAttribute(Qt.WA_DeleteOnClose)? It's already in AudioExportDialog.__init__. Besides, isn't it too late to set it after dlg.show()?

**Comment by wbsoft** [comment]
>Why did you add another call to setAttribute(Qt.WA_DeleteOnClose)? It's already in AudioExportDialog.init. Besides, isn't it too late to set it after dlg.show()?

Sorry, I didn't notice. I'll keep the one in the caller. I'd rather not have in in `__init__`, init just constructs the thing, and only the caller decides to use it only once and then throw it away. I will change it a little to demonstrate what I mean.

**Comment by proski** [comment]
That would be great. I was feeling uneasy about stuffing all code into the constructor, but I didn't know what belongs there and what doesn't. I'll be happy to check your commits and learn.

**Comment by wbsoft** [comment]
I tried to make a generic class and inherit it in `file_export/__init_.py`. See what you think of it. I also learn a lot of your coding! :-)

**Comment by proski** [comment]
Very nice!

**Pull request merged**
