### PR TITLE
fixes: #299 implemented autocomplete with tab key

### PR DESCRIPTION
**Pull request by jamesthechamp**
related to issue #299 
while typing one can use iterating through the suggestion list with TAB key 
please have a look on it.

### CODE REVIEW

**Comment by uliska** [comment]
Thank you for the PR.
It does what it promises (which is a small but really useful improvement for daily work :-) ), and I can't find anything wrong with the code.

So I suggest @wbsoft has a final look before merging it, otherwise I'd do it in a few days.

@jamesthechamp if you wish to continue on that track (of #299) I suggest you give a try at partial autocomplete.

For example, if you type `Dr` you get `DrumStaff` and `DrumVoice` as suggestions, which are equal up to the `Drum`

autocomplete

It would be even better if in that case the `um` would be added *and selected*. Hitting `Esc` or `Backsp` would cancel the whole operation while or remove the implicitly added text. Every other letter would be added *after* the selection. So if you write `Dr` you'd get the dropdown and `um` selected, so `S` or `V` would immediately select the right suggestion.

Please give a hint on whether you'd like to do that or not because in that case we'd postpone the merge and do it all together.

---

*(Just a general remark: even when you're forking the repository it would be good to work and submit your work in separate branches instead of on `master`)

**Comment by uliska** [comment]
Another (tiny but neat) improvement would be to automatically make the first element selected when the pop-up appears. Right now what happens is:

* I type `Dr`
* The suggestions pop up like in the image above
* When I hit `Enter` the first item is applied

This is actually correct behaviour but slightly incorrect display, as the first item should be highlighted already.

Consequently the first hit to TAB should not select the *first* item but the *second*.

**Comment by uliska** [comment]
@jamesthechamp If you are doing this because you're interested in GSoC and haven't done so (if I'm not mistaken) please introduce yourself on the Frescobaldi mailing list (maybe referencing this PR).

Otherwise just keep working on this please :-)

**Comment by jamesthechamp** [comment]
hey @uliska ,

i made changes and implemented autocomplete as you mention
now it partially autocomplete input as show following
peek 2017-03-23 18-07
and select first as popup opens as shown following
peek 2017-03-23 18-06
and sorry ... i should had made a new branch for issue i will take care of its from now on.
and sure i will shoot a mail introducing myself and my interest to project.

thanks for reviewing and providing guidance. :)

**Comment by uliska** [comment]
Thank you, this is becoming really nice!

But I have a wish that will make it somewhat more intuitive to use (actually this is what I had in mind but maybe I didn' make myself clear enough).

When the pop-up appears the common text should be already in the document, but selected, looking like this:
autocomplete

* TAB can then accept this partial suggestion (basically what you already have implemented)
* ENTER will accept the first (selected) item from the dropdown
* ESC will abort the process and (probably) remove the partial suggestion (or leave it selected, I don't know and really care)
* Typing any other character would accept the partial suggestion and continue to enter text. In the case of my image typing `V` would result in this state:

autocomplete

So entering `DrumVoice` would consist of the sequence `Dr` => `V` => `Enter`

---

Of course it would be nice if (as someone suggested) the match from input to word list would be case insensitive ...

**Comment by uliska** [comment]
Moved to https://github.com/wbsoft/frescobaldi/pull/922 to have it on a proper branch.

@jamesthechamp thank you for your contribution so far.

**Pull request closed without merging**
